Update Category and Tags metadata as discussed with Alex
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #165
Opened 2021-07-02 16:25 UTC by wpschaub

Consolidated tags to use
---------------------------
agile
architecture
automation
azure
azure-devops
code
devops
engineering
event
feature-flags
learning
pipelines
posters
quality
security
testing
tips
version-control
workflow
xp

Mappings used
-----------------
Agile(10)	agile
Automation(2)	>> automation
AzDO(7)	>> azure-devops
Azure AD(1)	>> azure
Azure Boards(4)	>> azure-devops, agile
Azure Pipelines(15)	>> azure-devops, pipelines
Azure Repos(1)	>> azure-devops, version-control
Cheat Sheets(4)	>> posters
CI(5)	>> pipelines
CloudOps(1)	>> devops
code(1)	>> code
Code-quality(1)	>> code, quality
Continuous Delivery (CD)(1)	>> pipelines
Continuous Integration (CI)(1)	>> pipelines
Continuous Learning(1)	>> learning
Design(1)	>> architecture
DevOps Mindset(1)	>> devops
DevOps(23)	>> devops
DevSecOps(1)	>> devops, security
Engineering Practices(1)	>> engineering
extract-method(1)	>> code, architecture
Extreme Programming(4)	>> code, xp
Feature Flags(3)	>> feature-flags
FrontEndDevelopment(1)	>> code, architecture
Git(1)	>> version-control
Infrastructure as Code(2)	>> x-as-code, pipelines
legacy-code(1)	>> code
Lunch and Learn(1)	>> learning
Pipeline as Code(8)	>> x-as-code, pipelines
Programming(3)	>> code
Scripting(1)	>> automation
Security(1)	>> security
Sysadmin(1)	>> automation
TDD(8)	>> code, testing
Tips(4)	t>> ips
workflow as code(1)	>> x-as-code, workflow
Workflow(1)	>> workflow
XP(3)	>> code, xp

2021-07-02 16:31 UTC, wpschaub commented
@wsbctechnicalblog we need to ensure that all future posts have at least two reviewers, with one core member, who is responsibile to validate the category and tags for each post.

2021-07-02 17:30 UTC, wsbctechnicalblog requested changes
I would prefer to keep the TDD tag.

2021-07-02 17:46 UTC, wpschaub commented
Hesitantly re-adding **tdd** - we have to be careful not to re-create a very granular (and noisy) tag schema.

2021-07-02 20:04 UTC, erwsch1 approved these changes

2021-07-03 15:39 UTC, wsbctechnicalblog approved these changes

2021-07-03 15:40 UTC, merged