Willys/381916-coe
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #223
Opened 2021-10-27 01:49 UTC by wpschaub

Releasing the first DRAFT of the CoE overview post to trigger open the feedback floodgates and to collaborate on a consistent format to use for the other event posts.

2021-10-27 01:59 UTC, adichourasiya submitted a review, later dismissed

2021-10-27 02:46 UTC, wsbctechnicalblog requested changes
So happy to see you've placed strong emphasis on the WHY! Without broadcasting clear, crisp expectations CoE stands less chances of moving the needle. Great way to formulate those.

Few minor requests: on the line 47, the last sentence "and products. content marketing engine for your organization" reads awkwardly. There is a full stop, but the word 'content' is not capitalized. Also, I'm not clear on what is the intention of that sentence? Maybe consider reworking it?

On line 69 there is a typo: hypothesist. Please fix it.

2021-10-27 03:31 UTC, wpschaub commented
@wsbctechnicalblog thank you for the feedback. I removed the sentence fragment ... must be a late-night brain fart that I could not figure out either. Also fixed the typo. Switching to working group next.

2021-10-27 18:02 UTC, sben101 commented on content/ceremony-center-of-enablement.md
> +
Should we mention governance? Who will be chairing these CoE meetings, etc.?

2021-10-27 18:04 UTC, sben101 reviewed
Looks great @wsbctechnicalblog I have added my one comment around governance/ chairing of these meetings and not sure if that is something we need to spell out?

2021-10-27 19:01 UTC, wpschaub commented on content/ceremony-center-of-enablement.md
> +
Governance is mentioned. We can add who will be chairing the CoE meetings, but as it is a closed, by invitation-only, event  I am thinking that the team can be self-organising and rotate the chair?

2021-10-27 19:08 UTC, wsbctechnicalblog commented on content/ceremony-center-of-enablement.md
> +
I'd leave that to the self-organizing forces within the Center of Enablement. Maybe they elect one member to chair the meetings, maybe they agree to rotate.

2021-10-27 20:50 UTC, adichourasiya submitted a review, later dismissed

2021-10-28 02:05 UTC, sben101 submitted a review, later dismissed
Thanks for the updates. This is looking good with the necessary information.

2021-10-29 02:17 UTC, wpschaub commented
I have included a "lifetime" section. Hope you like :)

2021-10-29 15:48 UTC, wsbctechnicalblog submitted a review, later dismissed

2021-10-29 17:15 UTC, wsbctechnicalblog submitted a review, later dismissed

2021-11-02 15:08 UTC, wsbctechnicalblog submitted a review, later dismissed
Fixed the typo on line 45.

2021-11-02 22:24 UTC, AndreKaminski reviewed
Looks good to me, thank you

2021-11-04 21:58 UTC, wpschaub commented
@wsbctechnicalblog I am done with this one. When we have two reviewer approvals and it is Monday, you can launch.

2021-11-04 22:22 UTC, wpschaub commented
@AndreKaminski @sben101 @asiebold69 @wsbctechnicalblog @adichourasiya please review this final PR to give it a final check-over. We are planning to trigger the wave of ceremony blogs and dogfood our (1) understanding of events, (2) overview, and working agreement posters, and (3) the supporting SharePoint site.

Here is link to view of blog post: https://github.com/wsbctechnicalblog/wsbctechnicalblog.github.io/blob/de4a10bca28dc79e7db674c952159eb82a26b78f/content/ceremony-center-of-enablement.md

Tic toc plan: 

- 11/8 Publish CoE blog
- 11/9 Working group blog
- 11/10 CoP blog
- 11/11 Dojo blog
- 11/12 Townhall blog
- 11/13 Overview blog

2021-11-04 22:22 UTC, wpschaub commented
@AndreKaminski @sben101 @asiebold69 @wsbctechnicalblog @adichourasiya please review this final PR to give it a final check-over. We are planning to trigger the wave of ceremony blogs and dogfood our (1) understanding of events, (2) overview, and working agreement posters, and (3) the supporting SharePoint site.

Here is [link](https://github.com/wsbctechnicalblog/wsbctechnicalblog.github.io/blob/de4a10bca28dc79e7db674c952159eb82a26b78f/content/ceremony-center-of-enablement.md) to quick view of blog post

Tic toc plan: 

- 11/8 Publish CoE blog
- 11/9 Working group blog
- 11/10 CoP blog
- 11/11 Dojo blog
- 11/12 Townhall blog
- 11/13 Overview blog

2021-11-04 22:23 UTC, wpschaub commented
@AndreKaminski @sben101 @asiebold69 @wsbctechnicalblog @adichourasiya please review this final PR to give it a final check-over. We are planning to trigger the wave of ceremony blogs and dogfood our (1) understanding of events, (2) overview, and working agreement posters, and (3) the supporting SharePoint site.

Here is link to view of blog post: https://github.com/wsbctechnicalblog/wsbctechnicalblog.github.io/blob/de4a10bca28dc79e7db674c952159eb82a26b78f/content/ceremony-center-of-enablement.md

Tic toc plan: 

- 11/8 Publish CoE blog
- 11/9 Working group blog
- 11/10 CoP blog
- 11/11 Dojo blog
- 11/12 Townhall blog
- 11/13 Overview blog

2021-11-04 23:52 UTC, AndreKaminski commented
@wpschaub in the diagram "Why we need CoE", could you make one of the CoE as "...", otherwise people might think that these are the only CoEs, but we have many more. Also I would suggest adding arrow between Working Group and CoP, as the outcomes of WG could go to both CoE and CoP

2021-11-05 00:58 UTC, wpschaub commented
@AndreKaminski I have revised the image. Looking for your review approve, to push this onto the launch pad.

2021-11-05 01:05 UTC, AndreKaminski approved these changes, later dismissed

2021-11-05 02:24 UTC, wsbctechnicalblog approved these changes, later dismissed

2021-11-08 19:26 UTC, merged