Willys/384144-approvals
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #227
Opened 2021-10-29 20:04 UTC by wpschaub

Tips and tricks post to talk about the approval gates and artifact filters, as DevSecOps ,mentioned that we are not consistent across the board. This post will summrise our streamlined approval process for EDO Ce and the community.

2021-10-29 21:43 UTC, wpschaub commented
@wsbctechnicalblog we need you and/or @rbeuthin, AND @604kev to review this PR before you pull the trigger.

Kevin, are you OK with the tone of the content talking about security engineers and does this summarize the pipeline hiccups we discussed?

2021-10-29 22:07 UTC, wsbctechnicalblog submitted a review, later dismissed

2021-11-01 22:27 UTC, 604kev requested changes

2021-11-01 22:27 UTC, 604kev commented on content/pipelines-streamlined-approvals.md
> +Leaving us with security review, which is based on automated vulnerability and quality scans and a few pairs of security engineer eyeballs. My colleague Kevin and I have been chatting about the [NEXU
Typo @wpschaub :) "boarder" -> "border"

2021-11-01 22:28 UTC, 604kev submitted a review, later dismissed
Typo resolved, looks good!

2021-11-02 13:20 UTC, wpschaub commented
@wsbctechnicalblog once you are happy, you can pull the trigger.

2021-11-02 18:03 UTC, wsbctechnicalblog reviewed
The date of this post is 2021-03-13. Is that correct?

2021-11-02 18:25 UTC, wpschaub commented
@wsbctechnicalblog date has been fixed to 11/2. Thank you for the catch!

2021-11-02 18:46 UTC, wsbctechnicalblog approved these changes

2021-11-02 18:47 UTC, merged