townhall events
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #232
Opened 2021-11-05 17:06 UTC by wsbctechnicalblog

2021-11-05 17:39 UTC, wpschaub commented
- Can you add the ceremony tag?
- Please also review the townhall working agreement poster and advise of changes.
- Happy to add the poster and download section when you are ready to receive a commit.

2021-11-05 18:23 UTC, wsbctechnicalblog commented
@wpschaub I'll open a new, simpler PR (forgot that this one also pushed unnecessary noise with generated HTML files), and I'll make the changes you requested. Thanks.

2021-11-08 16:42 UTC, wpschaub requested changes

2021-11-08 16:42 UTC, wpschaub commented on content/townhall.md
> +Tags: technical-excellence
@wsbctechnicalblog can you add the **ceremony** tag?

2021-11-08 16:42 UTC, wpschaub commented on content/townhall.md
> +There is also a possibility that the Townhall events may not be yielding the hoped-for results. In case of such eventuality, organizers should terminate the Townhall.
@wsbctechnicalblog please add overview and townhall pdf download section.

2021-11-08 18:17 UTC, wsbctechnicalblog commented
This PR is too messy, replaced it with a streamlined townhall events.

2021-11-08 18:17 UTC, closed without merging