first commit for analytics strategy
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #289
Opened 2022-01-04 22:29 UTC by adichourasiya

Hi team, wrote this article to explain analytics strategy document created last year. please have a look.

2022-01-05 03:34 UTC, wpschaub commented
@adichourasiya a few suggestions, whereby I am happy to make the changes for you:

- metadata date will need to be updated when you publish @wsbctechnicalblog.
- change filename to devops-analytics-strategy.md to create consistent kebab naming style.
- metadata slug should be same as filename, i.e. **devops-analytics-strategy**, for consistency.
- metadata author is incorrect. Change to **Aditya Chourasiya** and add entry to authors.
- metadata tags = learning, metrics, devops
- add bulleted lists for easier reading.
- add an explanation of what V2MOM stands for.

2022-01-05 05:59 UTC, wsbctechnicalblog submitted a review, later dismissed
I like this article, it's succinct and to the point. Nice to have such handy, easy to find reference on our blog.

Suggestion: @adichourasiya, maybe think about writing a followup article to talk more about how you see the current situation at WSBC regarding the overall analytics strategy?

2022-01-05 20:11 UTC, adichourasiya commented
I've made recommended changes in latest commit.

2022-01-07 10:36 UTC, wpschaub requested changes
A few minor tweaks requested.

2022-01-07 10:36 UTC, wpschaub commented on content/devops-analytics-strategy.md
> +![Vision](../images/vision.webp)
@adichourasiya image is not showing up. Can we convert if to *.png?

2022-01-07 10:36 UTC, wpschaub commented on content/devops-analytics-strategy.md
> +This article was intended to be written in [V2MoM](https://www.salesforce.com/blog/how-to-create-alignment-within-your-company/) format, however due to different organizational structure and needs, i
@adichourasiya please add two empty lines at the end.

2022-01-07 10:36 UTC, wpschaub commented on content/devops-analytics-strategy.md
> +Date: 2022-01-01
@wsbctechnicalblog you will have to update this date B4 publishing.

2022-01-09 02:52 UTC, wpschaub requested changes
@adichourasiya thank you for converting your images to png, which is more consistent with the rest of the images. That said, I finally figured out why your images are not showing up when viewing your md file. 

Please move your images from the /content/images folder to the /images folder.

cc @wsbctechnicalblog  another gremling we need to keep an eye on.

2022-01-19 04:39 UTC, wpschaub commented
@adichourasiya I fixed the images,  made a few format and spelling update. @wsbctechnicalblog  this is good to go for February 2nd.

2022-01-19 04:39 UTC, wpschaub approved these changes, later dismissed

2022-02-16 16:47 UTC, wpschaub commented
@adichourasiya are we good to go with this PR? I updated the publication date to 02/25.

2022-02-16 16:48 UTC, wpschaub approved these changes

2022-02-16 16:48 UTC, wpschaub commented
@adichourasiya are we good to go with this PR? I updated the publication date to 02/25.

2022-02-25 00:32 UTC, merged