1st version of Engineering Practice blog
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #415
Opened 2023-01-11 15:16 UTC by MerlinDarkstar

2023-01-11 15:33 UTC, wpschaub commented
@MerlinDarkstar initial review:

1. "...through the use of Sonar Cube " could be "...using SonarQube".
2. Not above, I think you mean SonarQube, not Sonar Cube :)
3. Can you remove the non *.md and *.png/jpg files from the Pull Request? I will add a gitignore file to the repo.
4. The section "# TDD and PowerShell Dojo Planning" is internal content - not suited for "public" post.

2023-01-11 19:16 UTC, wpschaub commented
@MerlinDarkstar I am still seeing the .vs folder and all its files in the PR.

Please add PR reviewers when you are ready for us to review :)

2023-01-12 17:29 UTC, danielrbroderick submitted a review, later dismissed

2023-01-12 17:40 UTC, wpschaub requested changes
@MerlinDarkstar make sure to focus these blogs on the non-WSBC community readers.

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +consistent and rohbust solutions that are of the highest quality and lowest possible technical dept (burden to maintain).
Typo - robust

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +These measurements will be calculated when the pipeline for a product is
How about changing "will be" to "... measurements are ..."?

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +We have begun the process of calculating various metrics on software created at
You could mention the four DevOps metrics, which are standard across DevOps ecosystem.

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +improvement and cultivate an open culture of experiment-fail-learn and share.
... and share, as discussed in [Fail, Learn, Reset!](/fail-learn-reset.html).

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +Check it out here: [EDO Ce Recommended Products Catalog.](https://wsdvuxstatic.blob.core.windows.net/demos/EEOPRODUCTCATALOGUE/index.html)
I would remove "If you'd like ... .html) paragraph and rather "tease" the reader with "we will explore the product catalog in a future discussion". Remember the blog posts are read by non-WSBC users and "EDO" makes no sense to them.

2023-01-12 17:40 UTC, wpschaub commented on content/EngineeringPractice-1.md
> +Phase III - Q1/Q2 Will tie this in with the Product Radar in the Technology
Again, the community reader has no context on TAP and DRG.  Be careful not to bleed internal programs in these posts, other than those we agreed to share, such as our pipelines.

2023-01-17 01:11 UTC, wpschaub approved these changes

2023-01-17 01:11 UTC, wpschaub commented
@MerlinDarkstar now that I know you are using VSE I understand all the noise that is checked in. Once merged, I will remove the .vs folder alltogether.

2023-01-17 16:32 UTC, danielrbroderick approved these changes

2023-01-18 02:37 UTC, merged