Naming Conventions
wsbctechnicalblog/wsbctechnicalblog.github.io pull request #425
Opened 2023-02-15 18:14 UTC by MerlinDarkstar

2023-02-16 06:41 UTC, wpschaub requested changes
@MerlinDarkstar added a few candid update suggestions and a few that must be cone, for example lowercase file and slug name - kebab-style.

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +Slug: EngineeringPractice-2
@MerlinDarkstar Can you change the slug and filename to engineering-practices-nuggets-convention?

Slug and file name should be the same, all lowercase. Title should be similar to slug with spaces instead of -'es.

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +# Why are Naming Conventions Important?
@MerlinDarkstar Please add an empty line between dividers - formatter is weird at times.

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +Tags: agile, architecture, code, code-quality, design, engineering, technical-excellence, tdd, tips, learning, innovation
@MerlinDarkstar can you trim down to 3-5 tags in this and your previous post? Otherwise we will dilute the tag value.

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +Lets explore these standards, and the patterns that we use *by convension* to improve our software and unlock automation.
Let's or Let us?

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +When we create *things* that have compound names - names that contain multple words combined into a single string - we may want to deliniate
@MerlinDarkstar again add an empty line between dividers and also between headings and text.

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +*Remeber* this is organization wide set of terms used for all sofware endevours - be careful when selecting terms that mean the same
REMEMBER?

2023-02-16 06:41 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +Date: 2023-01-18
I will tweak date when publishing. Planning for 2023.02.17.

2023-02-16 16:23 UTC, wpschaub commented on content/EngineeringPractice-2.md
> +Slug: EngineeringPractice-2
- Slug: engineering-practice-naming-conventions
- Filename: engineering-practice-naming-conventions.md

2023-02-16 16:28 UTC, wpschaub submitted a review, later dismissed
Thank you for making all the changes.

2023-02-16 23:42 UTC, 604kev approved these changes

2023-02-17 15:59 UTC, danielrbroderick approved these changes

2023-02-17 18:01 UTC, wsbctechnicalblog commented
Merged changes in separate PR.

2023-02-17 18:01 UTC, closed without merging